theme = "my-sonokai"

[editor]
line-number = "relative"
scrolloff = 2
cursorline = true
rulers = [80, 120]
true-color = true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

C-e = "scroll_down"
C-y = "scroll_up"

C-q = "file_picker_in_current_directory"

S-h = "goto_first_nonwhitespace"
S-l = "goto_line_end"

[keys.select]
S-h = "goto_first_nonwhitespace"
S-l = "goto_line_end"

#S-c = ["select_mode", "goto_line_end", "change_selection"]

[keys.insert]
C-l = "delete_char_forward"
